<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>VibeHarder</AssemblyName>
    <Title>Vibe Harder</Title>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <EnableDefaultAvaloniaItems>false</EnableDefaultAvaloniaItems>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Assets/app.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <PublishAot Condition="'$(PublishAot)' == ''">true</PublishAot>
    <StripSymbols>true</StripSymbols>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
    <DebugSymbols Condition="'$(Configuration)' == 'Release'">false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="*.cs" />
    <Compile Include="Program.cs;HeadlessHost.cs" />
    <AvaloniaResource Remove="**/*.axaml" />
    <AvaloniaXaml Remove="**/*.axaml" />
    <PackageReference Include="Avalonia.Wayland" Version="12.1.2" />
    <ProjectReference Include="../CodexManager.UI/CodexManager.UI.csproj" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Headless" Version="12.1.2" />
    <TrimmerRootDescriptor Include="TrimmerRoots.xml" />
    <None Update="Assets/Platforms/*.md;Assets/Brands/*.txt;Assets/Brands/*.md;Assets/Fonts/*.txt;Assets/app.*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
